sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t nkhishig/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nkhishig/docker-react npm run test